class ConflictException(Exception):
    pass


class UserNotFounException(Exception):
    pass
